# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: toxicity.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'toxicity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etoxicity.proto\x12\x08toxicity\"\x1e\n\x0e\x41nalyzeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\")\n\x0f\x41nalyzeResponse\x12\x16\n\x0etoxicity_score\x18\x01 \x01(\x01\x32U\n\x0fToxicityService\x12\x42\n\x0b\x41nalyzeText\x12\x18.toxicity.AnalyzeRequest\x1a\x19.toxicity.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'toxicity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=28
  _globals['_ANALYZEREQUEST']._serialized_end=58
  _globals['_ANALYZERESPONSE']._serialized_start=60
  _globals['_ANALYZERESPONSE']._serialized_end=101
  _globals['_TOXICITYSERVICE']._serialized_start=103
  _globals['_TOXICITYSERVICE']._serialized_end=188
# @@protoc_insertion_point(module_scope)
